package com.microsoft.pct.smartconversationalclient.luis;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISIntent {
    @com.fasterxml.jackson.annotation.JsonProperty("actions")
    private LUISAction[] _actions;

    public void setActions(LUISAction[] actions) {
        this._actions = actions;
    }

    public LUISAction[] getActions() {
        return _actions;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("intent")
    private String _intent;

    public void setIntent(String intent) {
        this._intent = intent;
    }

    public String getIntent() {
        return _intent;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("score")
    private Double _score;

    public void setScore(Double score) {
        this._score = score;
    }

    public Double getScore() {
        return _score;
    }

}