package com.microsoft.pct.smartconversationalclient.luis;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class LUISEntity {
    @com.fasterxml.jackson.annotation.JsonProperty("endIndex")
    private Integer _endindex;

    public void setEndindex(Integer endindex) {
        this._endindex = endindex;
    }

    public Integer getEndindex() {
        return _endindex;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("type")
    private String _type;

     public void setType(String type) {
        this._type = type;
    }

    public String getType() {
        return _type;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("startIndex")
    private Integer _startindex;

     public void setStartindex(Integer startindex) {
        this._startindex = startindex;
    }

    public Integer getStartindex() {
        return _startindex;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("score")
    private Double _score;

     public void setScore(Double score) {
        this._score = score;
    }

    public Double getScore() {
        return _score;
    }

    @com.fasterxml.jackson.annotation.JsonProperty("entity")
    private String _entity;

     public void setEntity(String entity) {
        this._entity = entity;
    }

    public String getEntity() {
        return _entity;
    }

}